const items = [
  {
    id: 1,
    title: "반지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/반지.png",
    likes: "20",
  },
  {
    id: 2,
    title: "청바지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/청바지.png",
    likes: "30",
  },
  {
    id: 3,
    title: "부츠",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/부츠.png",
    likes: "40",
  },
  {
    id: 4,
    title: "인형",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/인형.png",
    likes: "20",
  },
  {
    id: 5,
    title: "책",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/책.png",
    likes: "40",
  },
  {
    id: 6,
    title: "반지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/반지.png",
    likes: "15",
  },
  {
    id: 7,
    title: "청바지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/청바지.png",
    likes: "25",
  },
  {
    id: 8,
    title: "부츠",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/부츠.png",
    likes: "35",
  },
  {
    id: 9,
    title: "인형",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/인형.png",
    likes: "10",
  },
  {
    id: 10,
    title: "책",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/책.png",
    likes: "50",
  },
  {
    id: 11,
    title: "부츠",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/부츠.png",
    likes: "45",
  },
  {
    id: 12,
    title: "청바지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/청바지.png",
    likes: "30",
  },
  {
    id: 13,
    title: "반지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/반지.png",
    likes: "20",
  },
  {
    id: 14,
    title: "책",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/책.png",
    likes: "40",
  },
  {
    id: 15,
    title: "인형",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/인형.png",
    likes: "35",
  },
  {
    id: 16,
    title: "부츠",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/부츠.png",
    likes: "50",
  },
  {
    id: 17,
    title: "청바지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/청바지.png",
    likes: "20",
  },
  {
    id: 18,
    title: "반지",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/반지.png",
    likes: "30",
  },
  {
    id: 19,
    title: "책",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/책.png",
    likes: "45",
  },
  {
    id: 20,
    title: "인형",
    location: "올린 사람",
    date: "2024-08-18",
    imageUrl: "/images/인형.png",
    likes: "60",
  },
];

export default items;


  